// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'http://localhost:8080' | (string & {});
};

export type QuestionCreateRequest = {
    type: number;
    content: string;
    choices?: Array<string>;
    correctAnswer: string;
    score: number;
    difficulty: number;
    analysis?: string;
    tagIds?: Array<number>;
};

export type ApiResponseQuestionResponse = {
    code?: number;
    message?: string;
    data?: QuestionResponse;
};

export type QuestionResponse = {
    id?: number;
    type?: number;
    typeName?: string;
    content?: string;
    choices?: Array<string>;
    correctAnswer?: string;
    score?: number;
    difficulty?: number;
    analysis?: string;
    tags?: Array<TagResponse>;
    createdBy?: number;
    createdTime?: string;
    updatedTime?: string;
};

export type TagResponse = {
    id?: number;
    name?: string;
    type?: string;
};

export type PaperUpdateRequest = {
    title?: string;
    description?: string;
    totalScore?: number;
};

export type ApiResponsePaperDetailResponse = {
    code?: number;
    message?: string;
    data?: PaperDetailResponse;
};

export type PaperDetailResponse = {
    id?: number;
    title?: string;
    description?: string;
    totalScore?: number;
    questionCount?: number;
    status?: number;
    snapshotId?: number;
    createdBy?: number;
    createdTime?: string;
    updatedTime?: string;
    questions?: Array<PaperQuestionItemResponse>;
};

export type PaperQuestionItemResponse = {
    questionId?: number;
    number?: number;
    score?: number;
    questionType?: number;
    content?: string;
    choices?: Array<string>;
    correctAnswer?: string;
    defaultScore?: number;
    questionDeleted?: boolean;
};

export type UpdatePaperQuestionScoreRequest = {
    score: number;
};

export type ApiResponseVoid = {
    code?: number;
    message?: string;
    data?: unknown;
};

export type PaperOrderRequest = {
    questionIds: Array<number>;
};

export type ExamUpdateRequest = {
    title?: string;
    description?: string;
    paperId?: number;
    courseId?: number;
    classId?: number;
    startTime?: string;
    endTime?: string;
    durationMinutes?: number;
    allowLateMinutes?: number;
    antiCheatConfig?: JsonNode;
};

export type JsonNode = unknown;

export type ApiResponseExamDetailResponse = {
    code?: number;
    message?: string;
    data?: ExamDetailResponse;
};

export type ExamDetailResponse = {
    id?: number;
    title?: string;
    description?: string;
    paperId?: number;
    paperTitle?: string;
    courseId?: number;
    classId?: number;
    startTime?: string;
    endTime?: string;
    durationMinutes?: number;
    allowLateMinutes?: number;
    status?: number;
    published?: number;
    forceEnd?: number;
    antiCheatConfig?: JsonNode;
    snapshotId?: number;
    createdBy?: number;
    createdTime?: string;
    updatedTime?: string;
};

export type AutoSaveRequest = {
    version: number;
    answers?: JsonNode;
    marked?: Array<number>;
};

export type ApiResponseAutoSaveResponse = {
    code?: number;
    message?: string;
    data?: AutoSaveResponse;
};

export type AutoSaveResponse = {
    accepted?: boolean;
    version?: number;
    savedTime?: string;
};

export type ClassUpdateRequest = {
    name?: string;
    courseId?: number;
};

export type ApiResponseClassResponse = {
    code?: number;
    message?: string;
    data?: ClassResponse;
};

export type ClassResponse = {
    id?: number;
    name?: string;
    courseId?: number;
    teacherId?: number;
    createdBy?: number;
    createdTime?: string;
};

export type TransferRequest = {
    targetClassId: number;
};

export type TagCreateRequest = {
    name: string;
    type: string;
};

export type ApiResponseTagResponse = {
    code?: number;
    message?: string;
    data?: TagResponse;
};

export type BatchScoreRequest = {
    examIds: Array<number>;
    reason?: string;
};

export type ApiResponseListScoreActionItem = {
    code?: number;
    message?: string;
    data?: Array<ScoreActionItem>;
};

export type ScoreActionItem = {
    examId?: number;
    success?: boolean;
    message?: string;
};

export type ReviewHandleRequest = {
    action?: string;
    adjustedTotalScore?: number;
    reason?: string;
};

export type BatchDeleteQuestionsRequest = {
    ids: Array<number>;
};

export type ApiResponseBatchDeleteQuestionsResponse = {
    code?: number;
    message?: string;
    data?: BatchDeleteQuestionsResponse;
};

export type BatchDeleteQuestionsResponse = {
    succeeded?: Array<number>;
    failed?: Array<FailedItem>;
};

export type FailedItem = {
    id?: number;
    reason?: string;
};

export type PaperCreateRequest = {
    title: string;
    description?: string;
    totalScore: number;
};

export type ApiResponsePaperResponse = {
    code?: number;
    message?: string;
    data?: PaperResponse;
};

export type PaperResponse = {
    id?: number;
    title?: string;
    description?: string;
    totalScore?: number;
    questionCount?: number;
    status?: number;
    snapshotId?: number;
    createdBy?: number;
    createdTime?: string;
};

export type ApiResponsePaperSnapshotResponse = {
    code?: number;
    message?: string;
    data?: PaperSnapshotResponse;
};

export type PaperSnapshotResponse = {
    id?: number;
    paperId?: number;
    version?: number;
    totalScore?: number;
    questionCount?: number;
    content?: JsonNode;
    createdTime?: string;
};

export type AddPaperQuestionRequest = {
    questionId: number;
    score?: number;
};

export type ApiResponsePaperQuestionItemResponse = {
    code?: number;
    message?: string;
    data?: PaperQuestionItemResponse;
};

export type RandomDrawRequest = {
    rules: Array<Rule>;
};

export type Rule = {
    type?: number;
    difficulty?: number;
    tagIds?: Array<number>;
    count: number;
};

export type BatchAddPaperQuestionsRequest = {
    items: Array<Item>;
};

export type Item = {
    questionId: number;
    score?: number;
};

export type ApiResponseRandomDrawPreviewResponse = {
    code?: number;
    message?: string;
    data?: RandomDrawPreviewResponse;
};

export type DrawnQuestion = {
    id?: number;
    type?: number;
    typeName?: string;
    content?: string;
    score?: number;
    difficulty?: number;
};

export type RandomDrawPreviewResponse = {
    rules?: Array<RuleResult>;
    total?: number;
};

export type RuleResult = {
    ruleIndex?: number;
    count?: number;
    questions?: Array<DrawnQuestion>;
};

export type ExamCreateRequest = {
    title: string;
    description?: string;
    paperId: number;
    courseId?: number;
    classId?: number;
    startTime: string;
    endTime: string;
    durationMinutes: number;
    allowLateMinutes?: number;
    antiCheatConfig?: JsonNode;
};

export type ApiResponseExamResponse = {
    code?: number;
    message?: string;
    data?: ExamResponse;
};

export type ExamResponse = {
    id?: number;
    title?: string;
    paperId?: number;
    courseId?: number;
    classId?: number;
    startTime?: string;
    endTime?: string;
    durationMinutes?: number;
    allowLateMinutes?: number;
    status?: number;
    published?: number;
    forceEnd?: number;
    snapshotId?: number;
    createdBy?: number;
    createdTime?: string;
};

export type MakeupCreateRequest = {
    title?: string;
    startTime: string;
    endTime: string;
    durationMinutes: number;
    allowLateMinutes?: number;
    makeupScoreRule?: string;
    studentIds: Array<number>;
};

export type ApiResponseMakeupCreateResponse = {
    code?: number;
    message?: string;
    data?: MakeupCreateResponse;
};

export type MakeupCreateResponse = {
    examId?: number;
    title?: string;
    parentExamId?: number;
    makeupScoreRule?: string;
    candidateCount?: number;
};

export type ApiResponseSummarizeStats = {
    code?: number;
    message?: string;
    data?: SummarizeStats;
};

export type SummarizeStats = {
    summarized?: number;
    skipped?: number;
    examGraded?: boolean;
};

export type ScoreReviewApplyRequest = {
    reason?: string;
};

export type ApiResponseScoreReview = {
    code?: number;
    message?: string;
    data?: ScoreReview;
};

export type ScoreReview = {
    id?: number;
    examId?: number;
    studentId?: number;
    status?: number;
    reason?: string;
    result?: string;
    applyTime?: string;
    handleTime?: string;
    handlerId?: number;
    createdTime?: string;
};

export type ApiResponseFailureItem = {
    code?: number;
    message?: string;
    data?: FailureItem;
};

export type FailureItem = {
    submissionId?: number;
    studentId?: number;
    error?: string;
};

export type ManualScoreRequest = {
    objectiveScore: number;
};

export type SubjectiveScoreRequest = {
    submissionId: number;
    questionId: number;
    score: number;
    comment?: string;
    expectedVersion: number;
};

export type ApiResponseSubjectiveGradeRow = {
    code?: number;
    message?: string;
    data?: SubjectiveGradeRow;
};

export type SubjectiveGradeRow = {
    id?: number;
    submissionId?: number;
    examId?: number;
    studentId?: number;
    studentName?: string;
    questionId?: number;
    questionNumber?: number;
    studentAnswer?: string;
    suggestedScore?: number;
    suggestedDetail?: string;
    score?: number;
    comment?: string;
    graderId?: number;
    gradedTime?: string;
    version?: number;
    graded?: boolean;
};

export type ApiResponseGradingRunResponse = {
    code?: number;
    message?: string;
    data?: GradingRunResponse;
};

export type GradingRunResponse = {
    total?: number;
    success?: number;
    failed?: number;
    failures?: Array<FailureItem>;
};

export type SubmitRequest = {
    answers?: JsonNode;
    submitType?: string;
};

export type ApiResponseSubmitResponse = {
    code?: number;
    message?: string;
    data?: SubmitResponse;
};

export type SubmitResponse = {
    submissionId?: number;
    examId?: number;
    studentId?: number;
    status?: number;
    submitTime?: string;
    submitType?: number;
};

export type ApiResponseEnterExamResponse = {
    code?: number;
    message?: string;
    data?: EnterExamResponse;
};

export type EnterExamResponse = {
    examId?: number;
    examTitle?: string;
    submissionId?: number;
    status?: number;
    startTime?: string;
    deadlineTime?: string;
    serverTime?: string;
    remainingSeconds?: number;
    questions?: Array<QuestionView>;
    answers?: JsonNode;
    marked?: Array<number>;
    draftVersion?: number;
};

export type QuestionView = {
    number?: number;
    questionId?: number;
    type?: number;
    content?: string;
    choices?: JsonNode;
    score?: number;
};

export type BehaviorReportRequest = {
    eventType: string;
    eventData?: JsonNode;
    occurredTime?: string;
};

export type ApiResponseBehaviorReportResponse = {
    code?: number;
    message?: string;
    data?: BehaviorReportResponse;
};

export type BehaviorReportResponse = {
    warned?: boolean;
    severity?: number;
    severityName?: string;
    count?: number;
    message?: string;
};

export type ClassCreateRequest = {
    name: string;
    courseId?: number;
};

export type JoinStudentRequest = {
    userId: number;
};

export type RegisterRequest = {
    username: string;
    password: string;
    name: string;
    email?: string;
    roleType: string;
    inviteCode?: string;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type ApiResponseTokenResponse = {
    code?: number;
    message?: string;
    data?: TokenResponse;
};

export type TokenResponse = {
    accessToken?: string;
    refreshToken?: string;
    tokenType?: string;
    accessExpiresIn?: number;
    refreshExpiresIn?: number;
};

export type ResetPasswordRequest = {
    email: string;
    code: string;
    newPassword: string;
};

export type SendResetCodeRequest = {
    email: string;
};

export type ChangePasswordRequest = {
    oldPassword: string;
    newPassword: string;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type ApiResponseReplayReport = {
    code?: number;
    message?: string;
    data?: ReplayReport;
};

export type ReplayReport = {
    replayed?: number;
    parked?: number;
    remaining?: number;
};

export type InviteCodeCreateRequest = {
    note?: string;
};

export type ApiResponseInviteCodeResponse = {
    code?: number;
    message?: string;
    data?: InviteCodeResponse;
};

export type InviteCodeResponse = {
    id?: number;
    code?: string;
    note?: string;
    status?: number;
    usedCount?: number;
    createdBy?: number;
    createdTime?: string;
};

export type ApiResponseListTagResponse = {
    code?: number;
    message?: string;
    data?: Array<TagResponse>;
};

export type ApiResponseMyScoreResponse = {
    code?: number;
    message?: string;
    data?: MyScoreResponse;
};

export type MyScoreResponse = {
    examId?: number;
    examTitle?: string;
    objectiveScore?: number;
    subjectiveScore?: number;
    totalScore?: number;
    rank?: number;
    partialGraded?: number;
    reviewing?: boolean;
};

export type ApiResponseWrongQuestionPageResponse = {
    code?: number;
    message?: string;
    data?: WrongQuestionPageResponse;
};

export type ExamWrongQuestionsGroup = {
    examId?: number;
    examTitle?: string;
    examTime?: string;
    wrongQuestions?: Array<WrongQuestionItem>;
};

export type WrongQuestionItem = {
    examId?: number;
    examTitle?: string;
    examTime?: string;
    questionId?: number;
    questionNumber?: number;
    questionType?: string;
    questionContent?: string;
    choices?: Array<string>;
    myAnswer?: string;
    correctAnswer?: string;
    myScore?: number;
    fullScore?: number;
    analysis?: string;
    scoreDetail?: string;
};

export type WrongQuestionPageResponse = {
    total?: number;
    page?: number;
    size?: number;
    groups?: Array<ExamWrongQuestionsGroup>;
};

export type ApiResponseExamReviewResponse = {
    code?: number;
    message?: string;
    data?: ExamReviewResponse;
};

export type ExamReviewQuestionItem = {
    questionId?: number;
    questionNumber?: number;
    questionType?: string;
    questionContent?: string;
    choices?: Array<string>;
    myAnswer?: string;
    correctAnswer?: string;
    myScore?: number;
    fullScore?: number;
    graded?: boolean;
    analysis?: string;
    comment?: string;
    scoreDetail?: string;
};

export type ExamReviewResponse = {
    examId?: number;
    examTitle?: string;
    examTime?: string;
    studentName?: string;
    objectiveScore?: number;
    subjectiveScore?: number;
    totalScore?: number;
    rank?: number;
    partialGraded?: boolean;
    questions?: Array<ExamReviewQuestionItem>;
};

export type ApiResponseMakeupFinalScoreResponse = {
    code?: number;
    message?: string;
    data?: MakeupFinalScoreResponse;
};

export type MakeupFinalScoreResponse = {
    examId?: number;
    studentId?: number;
    finalScore?: number;
    reviewing?: boolean;
};

export type ApiResponseQuestionPageResponse = {
    code?: number;
    message?: string;
    data?: QuestionPageResponse;
};

export type QuestionPageResponse = {
    list?: Array<QuestionResponse>;
    total?: number;
    page?: number;
    size?: number;
};

export type ApiResponseListPaperResponse = {
    code?: number;
    message?: string;
    data?: Array<PaperResponse>;
};

export type ApiResponseListExamResponse = {
    code?: number;
    message?: string;
    data?: Array<ExamResponse>;
};

export type ApiResponseExamSnapshotResponse = {
    code?: number;
    message?: string;
    data?: ExamSnapshotResponse;
};

export type ExamSnapshotResponse = {
    id?: number;
    examId?: number;
    version?: number;
    exam?: JsonNode;
    paper?: JsonNode;
    createdTime?: string;
};

export type ApiResponseListMakeupCandidateItem = {
    code?: number;
    message?: string;
    data?: Array<MakeupCandidateItem>;
};

export type MakeupCandidateItem = {
    studentId?: number;
    studentName?: string;
    reason?: string;
};

export type AbsenceItemResponse = {
    studentId?: number;
    studentName?: string;
    markedTime?: string;
};

export type ApiResponseListAbsenceItemResponse = {
    code?: number;
    message?: string;
    data?: Array<AbsenceItemResponse>;
};

export type ApiResponseScorePreviewResponse = {
    code?: number;
    message?: string;
    data?: ScorePreviewResponse;
};

export type ScoreItem = {
    studentId?: number;
    studentName?: string;
    objectiveScore?: number;
    subjectiveScore?: number;
    totalScore?: number;
    rank?: number;
    partialGraded?: number;
};

export type ScorePreviewResponse = {
    examId?: number;
    examTitle?: string;
    summarizedCount?: number;
    partialGradedCount?: number;
    items?: Array<ScoreItem>;
};

export type ApiResponseScoreLeaderboardResponse = {
    code?: number;
    message?: string;
    data?: ScoreLeaderboardResponse;
};

export type LeaderboardItem = {
    rank?: number;
    displayName?: string;
    totalScore?: number;
    isMe?: boolean;
};

export type LeaderboardMyRow = {
    rank?: number;
    totalScore?: number;
    isMe?: boolean;
};

export type ScoreLeaderboardResponse = {
    examId?: number;
    examTitle?: string;
    myRow?: LeaderboardMyRow;
    top?: Array<LeaderboardItem>;
};

export type ApiResponseExamAnalysisReportResponse = {
    code?: number;
    message?: string;
    data?: ExamAnalysisReportResponse;
};

export type ClassOverview = {
    expectedCount?: number;
    actualCount?: number;
    absenceCount?: number;
    averageScore?: number;
    passRate?: number;
    scoreBands?: Array<ScoreBandItem>;
};

export type ExamAnalysisReportResponse = {
    classOverview?: ClassOverview;
    questionStats?: Array<QuestionStatItem>;
    tagWeakness?: Array<TagWeaknessItem>;
    hasTagDimension?: boolean;
    focusList?: Array<FocusStudentItem>;
};

export type FocusStudentItem = {
    studentId?: number;
    username?: string;
    studentName?: string;
    totalScore?: number;
};

export type QuestionStatItem = {
    order?: number;
    type?: string;
    fullScore?: number;
    averageScore?: number;
    scoreRate?: number;
    correctRate?: number;
    discrimination?: number;
    answeredCount?: number;
};

export type ScoreBandItem = {
    band?: string;
    count?: number;
};

export type TagWeaknessItem = {
    tagId?: number;
    tagName?: string;
    scoreRate?: number;
};

export type ApiResponseListScoreReview = {
    code?: number;
    message?: string;
    data?: Array<ScoreReview>;
};

export type ApiResponseMonitorOverviewResponse = {
    code?: number;
    message?: string;
    data?: MonitorOverviewResponse;
};

export type MonitorOverviewResponse = {
    examId?: number;
    examTitle?: string;
    examStatus?: number;
    totalStudents?: number;
    onlineCount?: number;
    offlineCount?: number;
    submittedCount?: number;
    abnormalCount?: number;
    totalQuestions?: number;
    students?: Array<MonitorStudentItem>;
};

export type MonitorStudentItem = {
    studentId?: number;
    studentName?: string;
    status?: string;
    answeredCount?: number;
    progressPercent?: number;
    abnormal?: boolean;
    abnormalEventCount?: number;
    maxSeverity?: number;
    lastAbnormalTime?: string;
};

export type ApiResponseSubjectiveGradePageResponse = {
    code?: number;
    message?: string;
    data?: SubjectiveGradePageResponse;
};

export type SubjectiveGradePageResponse = {
    rows?: Array<SubjectiveGradeRow>;
    total?: number;
    graded?: number;
};

export type ApiResponseListSubjectiveQuestionItem = {
    code?: number;
    message?: string;
    data?: Array<SubjectiveQuestionItem>;
};

export type SubjectiveQuestionItem = {
    questionId?: number;
    number?: number;
    content?: string;
    score?: number;
    totalStudents?: number;
    gradedStudents?: number;
};

export type ApiResponseGradingProgressResponse = {
    code?: number;
    message?: string;
    data?: GradingProgressResponse;
};

export type GradingProgressResponse = {
    submittedCount?: number;
    gradedCount?: number;
    failedCount?: number;
    pendingCount?: number;
    subjectiveTotal?: number;
    subjectiveGraded?: number;
    partialGradedCount?: number;
};

export type ApiResponseBehaviorLogPageResponse = {
    code?: number;
    message?: string;
    data?: BehaviorLogPageResponse;
};

export type BehaviorLogItem = {
    id?: number;
    examId?: number;
    studentId?: number;
    eventType?: string;
    severity?: number;
    severityName?: string;
    eventData?: JsonNode;
    eventTime?: string;
    createdTime?: string;
};

export type BehaviorLogPageResponse = {
    total?: number;
    page?: number;
    size?: number;
    items?: Array<BehaviorLogItem>;
};

export type ApiResponseBehaviorTimelineResponse = {
    code?: number;
    message?: string;
    data?: BehaviorTimelineResponse;
};

export type BehaviorTimelineResponse = {
    examId?: number;
    studentId?: number;
    total?: number;
    lowCount?: number;
    mediumCount?: number;
    highCount?: number;
    items?: Array<BehaviorLogItem>;
};

export type ApiResponseListExamListItem = {
    code?: number;
    message?: string;
    data?: Array<ExamListItem>;
};

export type ExamListItem = {
    examId?: number;
    title?: string;
    startTime?: string;
    endTime?: string;
    durationMinutes?: number;
    examStatus?: number;
    group?: string;
    canEnter?: boolean;
    submissionStatus?: number;
    remainingSeconds?: number;
};

export type ApiResponseClassPageResponse = {
    code?: number;
    message?: string;
    data?: ClassPageResponse;
};

export type ClassPageResponse = {
    list?: Array<ClassResponse>;
    total?: number;
    page?: number;
    size?: number;
};

export type ApiResponseListClassStudentItem = {
    code?: number;
    message?: string;
    data?: Array<ClassStudentItem>;
};

export type ClassStudentItem = {
    userId?: number;
    username?: string;
    name?: string;
    joinedTime?: string;
};

export type ApiResponseCurrentUserResponse = {
    code?: number;
    message?: string;
    data?: CurrentUserResponse;
};

export type CurrentUserResponse = {
    id?: number;
    username?: string;
    name?: string;
    email?: string;
    roles?: Array<string>;
    permissions?: Array<string>;
    mustChangePassword?: boolean;
};

export type ApiResponseListInviteCodeResponse = {
    code?: number;
    message?: string;
    data?: Array<InviteCodeResponse>;
};

export type ApiResponseListAuditLogResponse = {
    code?: number;
    message?: string;
    data?: Array<AuditLogResponse>;
};

export type AuditLogResponse = {
    id?: number;
    traceId?: string;
    userId?: number;
    username?: string;
    action?: string;
    ipAddress?: string;
    status?: string;
    details?: string;
    createdTime?: string;
};

export type DeleteData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/questions/{id}';
};

export type DeleteResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type DeleteResponse = DeleteResponses[keyof DeleteResponses];

export type DetailData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/questions/{id}';
};

export type DetailResponses = {
    /**
     * OK
     */
    200: ApiResponseQuestionResponse;
};

export type DetailResponse = DetailResponses[keyof DetailResponses];

export type UpdateData = {
    body: QuestionCreateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/questions/{id}';
};

export type UpdateResponses = {
    /**
     * OK
     */
    200: ApiResponseQuestionResponse;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];

export type Delete1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/papers/{id}';
};

export type Delete1Responses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type Delete1Response = Delete1Responses[keyof Delete1Responses];

export type Detail1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/papers/{id}';
};

export type Detail1Responses = {
    /**
     * OK
     */
    200: ApiResponsePaperDetailResponse;
};

export type Detail1Response = Detail1Responses[keyof Detail1Responses];

export type Update1Data = {
    body: PaperUpdateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/papers/{id}';
};

export type Update1Responses = {
    /**
     * OK
     */
    200: ApiResponsePaperDetailResponse;
};

export type Update1Response = Update1Responses[keyof Update1Responses];

export type UpdateQuestionScoreData = {
    body: UpdatePaperQuestionScoreRequest;
    path: {
        id: number;
        questionId: number;
    };
    query?: never;
    url: '/api/papers/{id}/questions/{questionId}/score';
};

export type UpdateQuestionScoreResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type UpdateQuestionScoreResponse = UpdateQuestionScoreResponses[keyof UpdateQuestionScoreResponses];

export type UpdateOrderData = {
    body: PaperOrderRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/papers/{id}/questions/order';
};

export type UpdateOrderResponses = {
    /**
     * OK
     */
    200: ApiResponsePaperDetailResponse;
};

export type UpdateOrderResponse = UpdateOrderResponses[keyof UpdateOrderResponses];

export type Delete2Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/exams/{id}';
};

export type Delete2Responses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type Delete2Response = Delete2Responses[keyof Delete2Responses];

export type Detail2Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/exams/{id}';
};

export type Detail2Responses = {
    /**
     * OK
     */
    200: ApiResponseExamDetailResponse;
};

export type Detail2Response = Detail2Responses[keyof Detail2Responses];

export type Update2Data = {
    body: ExamUpdateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/exams/{id}';
};

export type Update2Responses = {
    /**
     * OK
     */
    200: ApiResponseExamDetailResponse;
};

export type Update2Response = Update2Responses[keyof Update2Responses];

export type SaveDraftData = {
    body: AutoSaveRequest;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exam-taking/exams/{examId}/draft';
};

export type SaveDraftResponses = {
    /**
     * OK
     */
    200: ApiResponseAutoSaveResponse;
};

export type SaveDraftResponse = SaveDraftResponses[keyof SaveDraftResponses];

export type Delete3Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/classes/{id}';
};

export type Delete3Responses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type Delete3Response = Delete3Responses[keyof Delete3Responses];

export type Detail3Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/classes/{id}';
};

export type Detail3Responses = {
    /**
     * OK
     */
    200: ApiResponseClassResponse;
};

export type Detail3Response = Detail3Responses[keyof Detail3Responses];

export type Update3Data = {
    body: ClassUpdateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/classes/{id}';
};

export type Update3Responses = {
    /**
     * OK
     */
    200: ApiResponseClassResponse;
};

export type Update3Response = Update3Responses[keyof Update3Responses];

export type TransferData = {
    body: TransferRequest;
    path: {
        id: number;
        userId: number;
    };
    query?: never;
    url: '/api/classes/{id}/students/{userId}/transfer';
};

export type TransferResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type TransferResponse = TransferResponses[keyof TransferResponses];

export type ListData = {
    body?: never;
    path?: never;
    query?: {
        type?: string;
    };
    url: '/api/tags';
};

export type ListResponses = {
    /**
     * OK
     */
    200: ApiResponseListTagResponse;
};

export type ListResponse = ListResponses[keyof ListResponses];

export type CreateData = {
    body: TagCreateRequest;
    path?: never;
    query?: never;
    url: '/api/tags';
};

export type CreateResponses = {
    /**
     * OK
     */
    200: ApiResponseTagResponse;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type RevokeData = {
    body: BatchScoreRequest;
    path?: never;
    query?: never;
    url: '/api/scores/revoke';
};

export type RevokeResponses = {
    /**
     * OK
     */
    200: ApiResponseListScoreActionItem;
};

export type RevokeResponse = RevokeResponses[keyof RevokeResponses];

export type PublishData = {
    body: BatchScoreRequest;
    path?: never;
    query?: never;
    url: '/api/scores/publish';
};

export type PublishResponses = {
    /**
     * OK
     */
    200: ApiResponseListScoreActionItem;
};

export type PublishResponse = PublishResponses[keyof PublishResponses];

export type HandleData = {
    body: ReviewHandleRequest;
    path: {
        reviewId: number;
    };
    query?: never;
    url: '/api/score-reviews/{reviewId}/handle';
};

export type HandleResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type HandleResponse = HandleResponses[keyof HandleResponses];

export type PageData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
        type?: number;
        difficulty?: number;
        tagId?: number;
        keyword?: string;
    };
    url: '/api/questions';
};

export type PageResponses = {
    /**
     * OK
     */
    200: ApiResponseQuestionPageResponse;
};

export type PageResponse = PageResponses[keyof PageResponses];

export type Create1Data = {
    body: QuestionCreateRequest;
    path?: never;
    query?: never;
    url: '/api/questions';
};

export type Create1Responses = {
    /**
     * OK
     */
    200: ApiResponseQuestionResponse;
};

export type Create1Response = Create1Responses[keyof Create1Responses];

export type BatchDeleteData = {
    body: BatchDeleteQuestionsRequest;
    path?: never;
    query?: never;
    url: '/api/questions/batch-delete';
};

export type BatchDeleteResponses = {
    /**
     * OK
     */
    200: ApiResponseBatchDeleteQuestionsResponse;
};

export type BatchDeleteResponse = BatchDeleteResponses[keyof BatchDeleteResponses];

export type Page1Data = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/papers';
};

export type Page1Responses = {
    /**
     * OK
     */
    200: ApiResponseListPaperResponse;
};

export type Page1Response = Page1Responses[keyof Page1Responses];

export type Create2Data = {
    body: PaperCreateRequest;
    path?: never;
    query?: never;
    url: '/api/papers';
};

export type Create2Responses = {
    /**
     * OK
     */
    200: ApiResponsePaperResponse;
};

export type Create2Response = Create2Responses[keyof Create2Responses];

export type GetSnapshotData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/papers/{id}/snapshot';
};

export type GetSnapshotResponses = {
    /**
     * OK
     */
    200: ApiResponsePaperSnapshotResponse;
};

export type GetSnapshotResponse = GetSnapshotResponses[keyof GetSnapshotResponses];

export type GenerateSnapshotData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/papers/{id}/snapshot';
};

export type GenerateSnapshotResponses = {
    /**
     * OK
     */
    200: ApiResponsePaperSnapshotResponse;
};

export type GenerateSnapshotResponse = GenerateSnapshotResponses[keyof GenerateSnapshotResponses];

export type AddQuestionData = {
    body: AddPaperQuestionRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/papers/{id}/questions';
};

export type AddQuestionResponses = {
    /**
     * OK
     */
    200: ApiResponsePaperQuestionItemResponse;
};

export type AddQuestionResponse = AddQuestionResponses[keyof AddQuestionResponses];

export type CommitRandomDrawData = {
    body: RandomDrawRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/papers/{id}/questions/random';
};

export type CommitRandomDrawResponses = {
    /**
     * OK
     */
    200: ApiResponsePaperDetailResponse;
};

export type CommitRandomDrawResponse = CommitRandomDrawResponses[keyof CommitRandomDrawResponses];

export type AddQuestionsData = {
    body: BatchAddPaperQuestionsRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/papers/{id}/questions/batch';
};

export type AddQuestionsResponses = {
    /**
     * OK
     */
    200: ApiResponsePaperDetailResponse;
};

export type AddQuestionsResponse = AddQuestionsResponses[keyof AddQuestionsResponses];

export type PreviewDrawData = {
    body: RandomDrawRequest;
    path?: never;
    query?: never;
    url: '/api/papers/random-draw/preview';
};

export type PreviewDrawResponses = {
    /**
     * OK
     */
    200: ApiResponseRandomDrawPreviewResponse;
};

export type PreviewDrawResponse = PreviewDrawResponses[keyof PreviewDrawResponses];

export type Page2Data = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
        title?: string;
        status?: number;
    };
    url: '/api/exams';
};

export type Page2Responses = {
    /**
     * OK
     */
    200: ApiResponseListExamResponse;
};

export type Page2Response = Page2Responses[keyof Page2Responses];

export type Create3Data = {
    body: ExamCreateRequest;
    path?: never;
    query?: never;
    url: '/api/exams';
};

export type Create3Responses = {
    /**
     * OK
     */
    200: ApiResponseExamResponse;
};

export type Create3Response = Create3Responses[keyof Create3Responses];

export type Publish1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/exams/{id}/publish';
};

export type Publish1Responses = {
    /**
     * OK
     */
    200: ApiResponseExamDetailResponse;
};

export type Publish1Response = Publish1Responses[keyof Publish1Responses];

export type CreateMakeupData = {
    body: MakeupCreateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/exams/{id}/makeups';
};

export type CreateMakeupResponses = {
    /**
     * OK
     */
    200: ApiResponseMakeupCreateResponse;
};

export type CreateMakeupResponse = CreateMakeupResponses[keyof CreateMakeupResponses];

export type ForceEndData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/exams/{id}/force-end';
};

export type ForceEndResponses = {
    /**
     * OK
     */
    200: ApiResponseExamDetailResponse;
};

export type ForceEndResponse = ForceEndResponses[keyof ForceEndResponses];

export type SummarizeData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/scores/summarize';
};

export type SummarizeResponses = {
    /**
     * OK
     */
    200: ApiResponseSummarizeStats;
};

export type SummarizeResponse = SummarizeResponses[keyof SummarizeResponses];

export type ListByExamData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/score-reviews';
};

export type ListByExamResponses = {
    /**
     * OK
     */
    200: ApiResponseListScoreReview;
};

export type ListByExamResponse = ListByExamResponses[keyof ListByExamResponses];

export type ApplyData = {
    body: ScoreReviewApplyRequest;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/score-reviews';
};

export type ApplyResponses = {
    /**
     * OK
     */
    200: ApiResponseScoreReview;
};

export type ApplyResponse = ApplyResponses[keyof ApplyResponses];

export type RejudgeData = {
    body?: never;
    path: {
        examId: number;
        submissionId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/grading/submissions/{submissionId}/rejudge';
};

export type RejudgeResponses = {
    /**
     * OK
     */
    200: ApiResponseFailureItem;
};

export type RejudgeResponse = RejudgeResponses[keyof RejudgeResponses];

export type ManualScoreData = {
    body: ManualScoreRequest;
    path: {
        examId: number;
        submissionId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/grading/submissions/{submissionId}/manual-score';
};

export type ManualScoreResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type ManualScoreResponse = ManualScoreResponses[keyof ManualScoreResponses];

export type SaveSubjectiveScoreData = {
    body: SubjectiveScoreRequest;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/grading/subjective/save';
};

export type SaveSubjectiveScoreResponses = {
    /**
     * OK
     */
    200: ApiResponseSubjectiveGradeRow;
};

export type SaveSubjectiveScoreResponse = SaveSubjectiveScoreResponses[keyof SaveSubjectiveScoreResponses];

export type RunData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/grading/run';
};

export type RunResponses = {
    /**
     * OK
     */
    200: ApiResponseGradingRunResponse;
};

export type RunResponse = RunResponses[keyof RunResponses];

export type SubmitData = {
    body?: SubmitRequest;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exam-taking/exams/{examId}/submit';
};

export type SubmitResponses = {
    /**
     * OK
     */
    200: ApiResponseSubmitResponse;
};

export type SubmitResponse2 = SubmitResponses[keyof SubmitResponses];

export type EnterData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exam-taking/exams/{examId}/enter';
};

export type EnterResponses = {
    /**
     * OK
     */
    200: ApiResponseEnterExamResponse;
};

export type EnterResponse = EnterResponses[keyof EnterResponses];

export type ReportBehaviorData = {
    body: BehaviorReportRequest;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exam-taking/exams/{examId}/behavior';
};

export type ReportBehaviorResponses = {
    /**
     * OK
     */
    200: ApiResponseBehaviorReportResponse;
};

export type ReportBehaviorResponse = ReportBehaviorResponses[keyof ReportBehaviorResponses];

export type Page3Data = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/classes';
};

export type Page3Responses = {
    /**
     * OK
     */
    200: ApiResponseClassPageResponse;
};

export type Page3Response = Page3Responses[keyof Page3Responses];

export type Create4Data = {
    body: ClassCreateRequest;
    path?: never;
    query?: never;
    url: '/api/classes';
};

export type Create4Responses = {
    /**
     * OK
     */
    200: ApiResponseClassResponse;
};

export type Create4Response = Create4Responses[keyof Create4Responses];

export type ListStudentsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/classes/{id}/students';
};

export type ListStudentsResponses = {
    /**
     * OK
     */
    200: ApiResponseListClassStudentItem;
};

export type ListStudentsResponse = ListStudentsResponses[keyof ListStudentsResponses];

export type JoinStudentData = {
    body: JoinStudentRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/classes/{id}/students';
};

export type JoinStudentResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type JoinStudentResponse = JoinStudentResponses[keyof JoinStudentResponses];

export type RegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/api/auth/register';
};

export type RegisterResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type RefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/api/auth/refresh';
};

export type RefreshResponses = {
    /**
     * OK
     */
    200: ApiResponseTokenResponse;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type ResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/password/reset';
};

export type ResetPasswordResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type SendResetCodeData = {
    body: SendResetCodeRequest;
    path?: never;
    query?: never;
    url: '/api/auth/password/reset-code';
};

export type SendResetCodeResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type SendResetCodeResponse = SendResetCodeResponses[keyof SendResetCodeResponses];

export type ChangePasswordData = {
    body: ChangePasswordRequest;
    path?: never;
    query?: never;
    url: '/api/auth/password/change';
};

export type ChangePasswordResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type ChangePasswordResponse = ChangePasswordResponses[keyof ChangePasswordResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginResponses = {
    /**
     * OK
     */
    200: ApiResponseTokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type KickUserData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/admin/users/{userId}/kick';
};

export type KickUserResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type KickUserResponse = KickUserResponses[keyof KickUserResponses];

export type ReplayData = {
    body?: never;
    path?: never;
    query?: {
        max?: number;
    };
    url: '/api/admin/mq/dlq/replay';
};

export type ReplayResponses = {
    /**
     * OK
     */
    200: ApiResponseReplayReport;
};

export type ReplayResponse = ReplayResponses[keyof ReplayResponses];

export type ListInviteCodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/invite-codes';
};

export type ListInviteCodesResponses = {
    /**
     * OK
     */
    200: ApiResponseListInviteCodeResponse;
};

export type ListInviteCodesResponse = ListInviteCodesResponses[keyof ListInviteCodesResponses];

export type CreateInviteCodeData = {
    body?: InviteCodeCreateRequest;
    path?: never;
    query?: never;
    url: '/api/admin/invite-codes';
};

export type CreateInviteCodeResponses = {
    /**
     * OK
     */
    200: ApiResponseInviteCodeResponse;
};

export type CreateInviteCodeResponse = CreateInviteCodeResponses[keyof CreateInviteCodeResponses];

export type InvalidateInviteCodeData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/admin/invite-codes/{id}/invalidate';
};

export type InvalidateInviteCodeResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type InvalidateInviteCodeResponse = InvalidateInviteCodeResponses[keyof InvalidateInviteCodeResponses];

export type MyScoreData = {
    body?: never;
    path?: never;
    query: {
        examId: number;
    };
    url: '/api/scores/my';
};

export type MyScoreResponses = {
    /**
     * OK
     */
    200: ApiResponseMyScoreResponse;
};

export type MyScoreResponse2 = MyScoreResponses[keyof MyScoreResponses];

export type MyWrongQuestionsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
    };
    url: '/api/scores/my/wrong-questions';
};

export type MyWrongQuestionsResponses = {
    /**
     * OK
     */
    200: ApiResponseWrongQuestionPageResponse;
};

export type MyWrongQuestionsResponse = MyWrongQuestionsResponses[keyof MyWrongQuestionsResponses];

export type MyExamReviewData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/scores/my/exams/{examId}/review';
};

export type MyExamReviewResponses = {
    /**
     * OK
     */
    200: ApiResponseExamReviewResponse;
};

export type MyExamReviewResponse = MyExamReviewResponses[keyof MyExamReviewResponses];

export type MyMakeupFinalScoreData = {
    body?: never;
    path?: never;
    query: {
        examId: number;
    };
    url: '/api/scores/makeup-final';
};

export type MyMakeupFinalScoreResponses = {
    /**
     * OK
     */
    200: ApiResponseMakeupFinalScoreResponse;
};

export type MyMakeupFinalScoreResponse = MyMakeupFinalScoreResponses[keyof MyMakeupFinalScoreResponses];

export type GetSnapshot1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/exams/{id}/snapshot';
};

export type GetSnapshot1Responses = {
    /**
     * OK
     */
    200: ApiResponseExamSnapshotResponse;
};

export type GetSnapshot1Response = GetSnapshot1Responses[keyof GetSnapshot1Responses];

export type MakeupEligibleData = {
    body?: never;
    path: {
        id: number;
    };
    query?: {
        passLine?: number;
    };
    url: '/api/exams/{id}/makeup-eligible';
};

export type MakeupEligibleResponses = {
    /**
     * OK
     */
    200: ApiResponseListMakeupCandidateItem;
};

export type MakeupEligibleResponse = MakeupEligibleResponses[keyof MakeupEligibleResponses];

export type AbsencesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/exams/{id}/absences';
};

export type AbsencesResponses = {
    /**
     * OK
     */
    200: ApiResponseListAbsenceItemResponse;
};

export type AbsencesResponse = AbsencesResponses[keyof AbsencesResponses];

export type PublishPreviewData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/scores/publish-preview';
};

export type PublishPreviewResponses = {
    /**
     * OK
     */
    200: ApiResponseScorePreviewResponse;
};

export type PublishPreviewResponse = PublishPreviewResponses[keyof PublishPreviewResponses];

export type MakeupFinalScoreData = {
    body?: never;
    path: {
        examId: number;
        studentId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/scores/makeup-final/{studentId}';
};

export type MakeupFinalScoreResponses = {
    /**
     * OK
     */
    200: ApiResponseMakeupFinalScoreResponse;
};

export type MakeupFinalScoreResponse2 = MakeupFinalScoreResponses[keyof MakeupFinalScoreResponses];

export type LeaderboardData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/scores/leaderboard';
};

export type LeaderboardResponses = {
    /**
     * OK
     */
    200: ApiResponseScoreLeaderboardResponse;
};

export type LeaderboardResponse = LeaderboardResponses[keyof LeaderboardResponses];

export type ExportQuestionStatsData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/scores/export/question-stats';
};

export type ExportQuestionStatsResponses = {
    /**
     * OK
     */
    200: string;
};

export type ExportQuestionStatsResponse = ExportQuestionStatsResponses[keyof ExportQuestionStatsResponses];

export type ExportPersonalData = {
    body?: never;
    path: {
        examId: number;
        studentId: number;
    };
    query?: {
        format?: string;
    };
    url: '/api/exams/{examId}/scores/export/personal/{studentId}';
};

export type ExportPersonalResponses = {
    /**
     * OK
     */
    200: string;
};

export type ExportPersonalResponse = ExportPersonalResponses[keyof ExportPersonalResponses];

export type ExportQuestionDetailData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/scores/export/detail';
};

export type ExportQuestionDetailResponses = {
    /**
     * OK
     */
    200: string;
};

export type ExportQuestionDetailResponse = ExportQuestionDetailResponses[keyof ExportQuestionDetailResponses];

export type ExportClassSheetData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/scores/export/class-sheet';
};

export type ExportClassSheetResponses = {
    /**
     * OK
     */
    200: string;
};

export type ExportClassSheetResponse = ExportClassSheetResponses[keyof ExportClassSheetResponses];

export type AnalysisReportData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/scores/analysis-report';
};

export type AnalysisReportResponses = {
    /**
     * OK
     */
    200: ApiResponseExamAnalysisReportResponse;
};

export type AnalysisReportResponse = AnalysisReportResponses[keyof AnalysisReportResponses];

export type OverviewData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/monitor/overview';
};

export type OverviewResponses = {
    /**
     * OK
     */
    200: ApiResponseMonitorOverviewResponse;
};

export type OverviewResponse = OverviewResponses[keyof OverviewResponses];

export type SubjectiveRowsData = {
    body?: never;
    path: {
        examId: number;
    };
    query: {
        questionId: number;
        page?: number;
        size?: number;
        onlyUngraded?: boolean;
        name?: string;
        submissionId?: number;
    };
    url: '/api/exams/{examId}/grading/subjective';
};

export type SubjectiveRowsResponses = {
    /**
     * OK
     */
    200: ApiResponseSubjectiveGradePageResponse;
};

export type SubjectiveRowsResponse = SubjectiveRowsResponses[keyof SubjectiveRowsResponses];

export type SubjectiveQuestionsData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/grading/subjective/questions';
};

export type SubjectiveQuestionsResponses = {
    /**
     * OK
     */
    200: ApiResponseListSubjectiveQuestionItem;
};

export type SubjectiveQuestionsResponse = SubjectiveQuestionsResponses[keyof SubjectiveQuestionsResponses];

export type ProgressData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exams/{examId}/grading/progress';
};

export type ProgressResponses = {
    /**
     * OK
     */
    200: ApiResponseGradingProgressResponse;
};

export type ProgressResponse = ProgressResponses[keyof ProgressResponses];

export type Page4Data = {
    body?: never;
    path: {
        examId: number;
    };
    query?: {
        studentId?: number;
        eventType?: string;
        severity?: number;
        page?: number;
        size?: number;
    };
    url: '/api/exams/{examId}/behavior-logs';
};

export type Page4Responses = {
    /**
     * OK
     */
    200: ApiResponseBehaviorLogPageResponse;
};

export type Page4Response = Page4Responses[keyof Page4Responses];

export type TimelineData = {
    body?: never;
    path: {
        examId: number;
    };
    query: {
        studentId: number;
    };
    url: '/api/exams/{examId}/behavior-logs/timeline';
};

export type TimelineResponses = {
    /**
     * OK
     */
    200: ApiResponseBehaviorTimelineResponse;
};

export type TimelineResponse = TimelineResponses[keyof TimelineResponses];

export type MyExamsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/exam-taking/exams';
};

export type MyExamsResponses = {
    /**
     * OK
     */
    200: ApiResponseListExamListItem;
};

export type MyExamsResponse = MyExamsResponses[keyof MyExamsResponses];

export type PaperData = {
    body?: never;
    path: {
        examId: number;
    };
    query?: never;
    url: '/api/exam-taking/exams/{examId}/paper';
};

export type PaperResponses = {
    /**
     * OK
     */
    200: ApiResponseEnterExamResponse;
};

export type PaperResponse2 = PaperResponses[keyof PaperResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeResponses = {
    /**
     * OK
     */
    200: ApiResponseCurrentUserResponse;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type AuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        size?: number;
        username?: string;
        action?: string;
    };
    url: '/api/admin/audit-logs';
};

export type AuditLogsResponses = {
    /**
     * OK
     */
    200: ApiResponseListAuditLogResponse;
};

export type AuditLogsResponse = AuditLogsResponses[keyof AuditLogsResponses];

export type Delete4Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tags/{id}';
};

export type Delete4Responses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type Delete4Response = Delete4Responses[keyof Delete4Responses];

export type RemoveQuestionData = {
    body?: never;
    path: {
        id: number;
        questionId: number;
    };
    query?: never;
    url: '/api/papers/{id}/questions/{questionId}';
};

export type RemoveQuestionResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type RemoveQuestionResponse = RemoveQuestionResponses[keyof RemoveQuestionResponses];

export type RemoveStudentData = {
    body?: never;
    path: {
        id: number;
        userId: number;
    };
    query?: never;
    url: '/api/classes/{id}/students/{userId}';
};

export type RemoveStudentResponses = {
    /**
     * OK
     */
    200: ApiResponseVoid;
};

export type RemoveStudentResponse = RemoveStudentResponses[keyof RemoveStudentResponses];
